/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.mayflower.java101;

import org.junit.Test;

import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;

public class AppFrameTest {

    @Test public void testFrameCreation() {

        AppFrame frame = new AppFrame();


        assertNotNull( "Frame exists", frame );

    }
}
